select from_utc_timestamp(current_timestamp,'US/Central') as recorded_timestamp,
('{source_system_name}') as source_system_name,
generatesameuuid(concat(a.source_system_name,':',coalesce(a.source_activity_id,'NULL'),':',coalesce(a.activity_type,'NULL'),':',coalesce(a.activity_amount_type,'NULL'))) as documentid,
a.fkcontractdocumentid,
f.documentid as fkfunddocumentid,
('{source_system_name}') as sourcesystemname,
a.key_qualifier as contractnumber,
a.source_system_activity_id as activitysourcemactivityid,
a.source_activity_id as sourceactivityid,
a.activity_type as activitytype,
a.activity_amount_type as activityamounttype,
cast(a.activity_effective_date as date) as activityeffectivedate,
cast(a.activity_reported_date as date) as activityreporteddate,
a.fund_number as fundnumber,
a.activity_general_ledger_application_area_code as activitygeneralledgerapplicationareacode,
a.activity_general_ledger_source_code as activitygeneralledgersourcecode,
a.activity_source_transaction_code as activitysourcetransactioncode,
a.activity_money_method as activitymoneymethod,
a.activity_first_year_renewal_indicator as activityfirstyearrenewalindicator,
a.activity_type_group as activitytypegroup,
a.activity_amount as activityamount,
a.source_activity_parent_id as activitysourceactivityparentid,
a.activity_source_originating_user_id as activitysourceoriginatinguserid,
a.activity_source_suspense_reference_number as activitysourcesuspensereferencenumber,
a.activity_1035exchange_indicator as activity1035exchangeindicator,
a.activity_source_claim_identifier as activitysourceclaimidentifier,
a.contract_administration_location_code as contractadministrationlocationcode,
a.source_fund_identifier as fundsourcefundidentifier,
a.activity_withholding_tax_jurisdiction as activitywithholdingtaxjurisdiction,
a.activity_source_accounting_memo_code as activitysourceaccountingmemocode,
a.activity_reversal_code as activityreversalcode,
a.legal_company_code as activitylegalcompanycode,
a.source_legal_entity_code as activitysourcelegalentitycode,
a.activity_deposit_source_batch_identifier as activitydepositsourcebatchidentifier,
a.activity_source_accounting_deviator as activitysourceaccountingdeviator,
cast(a.operationcode as string) as operationcode,
cast('{cycle_date}' as date) as cycle_date,
cast('{batchid}' as int) as batch_id
from gdqp5activity a
left join a1mfund f
on a.fund_number = f.fundnumber
and a.contract_administration_location_code = f.fundregion;
