SELECT CNTRT_ADMN_LOC_CD,
       CNTRT_SRC_SYS_NM_SRC,
       ADMN_PRCSS_LEG_ENTY_CD_SRC
FROM TIME.SCH.LKP_CNTRT_ADMN_LOC_CD
WHERE ADMN_PRCSS_LEG_ENTY_CD_SRC = '~'
  AND CNTRT_SRC_SYS_NM_SRC = 'Bestow'
