DROP TABLE IF EXISTS ${databasename}.oraclefah_subledgerjournallinedetail;
CREATE EXTERNAL TABLE ${databasename}.oraclefah_subledgerjournallinedetail
(
 recorded_timestamp timestamp,
 source_system_name string,
 generalledgerledgerjournalheaderid string,
 generalledgerledgerjournalheaderdescription string,
 generalledgerledgerjournallinenumber BIGINT,
 generalledgerledgerjournallinedescription string,
 generalledgerjournalname string,
 generalledgerjournalbatchname string,
 generalledgerjournallinenumber integer,
 generalledgerjournalsourcecategory string,
 glscaledgercode string,
 glscaledgerdescription string,
 generalledgeraccountingperiod string,
 activityreporteddate timestamp,
 generalledgersubledgerpostdate timestamp,
 generalledgerreversalindicator string,
 generalledgersubledgername string,
 generalledgersubledgereventtypecode string,
 chartofaccountscompanycode string,
 chartofaccountslineofbusinesscode string,
 chartofaccountsdepartmentcode string,
 chartofaccountsaccountcode string,
 chartofaccountsproductcode string,
 chartofaccountsintercompanycode string,
 chartofaccountssummaryproductcode string,
 generalledgertransactioncurrencycode string,
 generalledgertransactioncurrencyamount decimal(18,6),
 generalledgercurrencyconversionratedate date,
 generalledgercurrencyconversionratetype string,
 generalledgerreportingcurrencyexchangerate decimal(18,6),
 generalledgerreportingcurrencycode string,
 generalledgerreportingcurrencyamount decimal(18,6),
 generalledgersubledgerjournalcreateddate timestamp,
 generalledgersubledgerjournalcreator string,
 generalledgersubledgerjournalupdateddate timestamp,
 generalledgersubledgerjournallastupdatedby string,
 sourcesystemname string,
 contractnumber string,
 sourcefundidentifier string,
 insuranceactivitynumber string,
 insurancecounterpartyreportinggroup string,
 insurancecounterpartycode string,
 originatinggeneralledgerdescription1 string,
 originatinggeneralledgerdescription2 string,
 originatinggeneralledgerprojectcode string,
 activitygeneralledgerapplicationarea string,
 activitygeneralledgersourcecode string,
 generalledgerdatatype string,
 generalledgerreversaldate date,
 activityaccountingid string,
 generalledgeroriginalsubledgername string,
 contractsourcemarketorganizationcode string,
 ifrs17reportingcashflowtype string,
 activitysourcetransactioncode string,
 checknumber string,
 groupcontractnumber string,
 sourcesystemgroupcontractnumber string,
 sourcesystemglscaledgercode string,
 contractissuedate date,
 insurancecounterpartytype string,
 ifrs17measurementmodel string,
 activitysourcetransactiontype string,
 sourcelegalentitycode string,
 generalledgersubledgeraccountingclass string,
 cessionidentifier string,
 typeofbusinessinsured string,
 insurancegroupindividualflag string,
 insurancecountrycode string,
 insurancecontractidentifier string,
 primaryinsuredpostalcode string,
 transactionclass string,
 generalledgeraccountingcenterdeviator string,
 contracteffectivedate date,
 activitygroup string,
 activitysubtype string,
 transactionaddresstype string,
 transactionchargestype string,
 transactioncosttype string,
 transactionexptype string,
 generalledgerdetailedbicreditindicator string,
 contractissuage string,
 contractdurationinyears string
)
PARTITIONED BY (
 cycle_date date,
 batch_id int
)
ROW FORMAT SERDE
 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
 '${s3bucketname}/${projectname}/curated/erpdw/oraclefah/oraclefah_subledgerjournallinedetail';
MSCK REPAIR TABLE ${databasename}.oraclefah_subledgerjournallinedetail SYNC PARTITIONS;
