SELECT CNTRT_ADMN_LOC_CD,
       CNTRT_SRC_SYS_NM_SRC,
       ADMN_PRCS_LGL_ENTY_CD_SRC
FROM TIME_SCH.LKP_CNTRT_ADMN_LOC_CD
WHERE ADMN_PRCS_LGL_ENTY_CD_SRC = '~'
  AND CNTRT_SRC_SYS_NM_SRC = 'Bestow'
