SELECT ORIGNTNG_SRC_SYS_NM,
       ORIGNTNG_CNTRCT_NBR,
       IFRS17_PRTFOLIO,
       IFRS17_COHORT,
       IFRS17_PRFTBLY,
       IFRS17_GRPNG
FROM TIME_SCH.LKP_IFRS17_CNTRT_TAG_VW
WHERE ORIGNTNG_SRC_SYS_NM = 'Bestow'
