SELECT ORIG_SRC_SYS_NM,
       CNTRT_PLN_CD,
       CNTRT_PRDCT_TYP_NM,
       IFRS17_COHORT_STRT_DT,
       IFRS17_COHORT_END_DT,
       IFRS17_COHORT,
       IFRS17PORTFOLIO,
       IFRS17GROUPING
FROM TIME_SCH.LKP_IFRS17_NB_PRT_CHRT
WHERE (to_timestamp('{cycle_date}', 'yyyy-MM-dd') BETWEEN LKP_IFRS17_NB_PRT_CHRT.IFRS17_COHORT_STRT_DT AND LKP_IFRS17_NB_PRT_CHRT.IFRS17_COHORT_END_DT)
  AND ORIG_SRC_SYS_NM = 'Bestow'
