SELECT recorded_timestamp,
       source_system_name,
       documentid,
       sourcesystemname,
       contractadministrationlocationcode,
       contractissuedate,
       sourcelegalentitycode,
       contractplancode,
       contracteffectivedate,
       contractlegalcompanycode,
       contractreportinglineofbusiness,
       contractstatusreasoncode,
       contractstatuscode,
       contractqualifiedindicator,
       contractsopsisindicator,
       contractgroupingindicator,
       contractcoverageid,
       contractparticipationindicator,
       contractsourcemarketingorganizationcode,
       contractproducttypename,
       originatingcontractnumber,
       originatingsourcesystemname,
       coalesce(contractifrs17portfolio,'@') as contractifrs17portfolio,
       coalesce(contractifrs17grouping,'@') as contractifrs17grouping,
       coalesce(contractifrs17cohort,'@') as contractifrs17cohort,
       coalesce(contractifrs17profitability,'@') as contractifrs17profitability,
       cycle_date,
       batch_id
FROM ifrscontracttagging
