select 
from_utc_timestamp(current_timestamp,'US/Central') as recorded_timestamp,
'{source_system_name}' as source_system_name,
w1.uiddocumentgroupkey as documentid,
w1.contractoptiondocumentid as fkcontractoptiondocumentid,
w1.contractdocumentid as fkcontractdocumentid,
w1.documentid as fkfunddocumentid,
'{source_system_name}' as sourcesystemname,
contractnumber,
cast(w1.contractoptionsourcesystemordinalposition as int) as contractoptionsourcesystemordinalposition,
w1.contractoptionfundnumber,
w1.contractoptionfundclassindicator,
w1.contractoptionfundbundledinvestmentmanagementfeeamount,
w1.contractoptionfundbundledinvestmentadvisorfeeamount,
w1.contractoptionfundbundledinvestmentdealerfeeamount,
w1.contractoptionfundbundledinvestmenttrailcommissionfeeamount,
w1.contractoptionfundbundledgainlossamount,
w1.contractoptionfundsalesfeeamount,
w1.contractoptionfundgapvalue,
cast(w1.contractoptionfundvalue as decimal(18,6)) as contractoptionfundvalue,
w1.contractoptionfundseparateaccountvalueindex1,
w1.contractoptionfundseparateaccountvalueindex2,
w1.contractoptionfundseparateaccountvalueindex3,
w1.contractoptionfundseparateaccountvalueindex4,
w1.contractoptionfundseparateaccountvalueindex5,
w1.contractoptionfundseparateaccountvalueindex6,
w1.contractoptionfundseparateaccountvalueindex7,
w1.contractoptionfundseparateaccountvalueindex8,
w1.contractoptionfundseparateaccountvalueindex9,
w1.contractoptionfundseparateaccountvalueindex10,
w1.contractoptionfundsafevalue,
w1.contractoptionfunddynamicseparateaccountvalue,
w1.contractoptionfundselfhedgingseparateaccountvalue,
w1.initialpremium,
cast(w1.surrendervalueamount as decimal(18,6)) as surrendervalueamount,
w1.modelinggeneralpremium,
w1.operationcode,
cast('{cycle_date}' as date) as cycle_date,
cast({batchid} as int) as batch_id
from 
wrkdoccontractoptionfundsrcp5 w1
left join almfund f on 
w1.contractoptionfundnumber = f.fundnumber
and w1.contractadministrationlocationcode = f.fundregion