SELECT
EFF_STRT_DT,
EFF_STOP_DT,
SRC_LGL_ENTY_CD,
LGL_ENTY_CD
FROM TIME_SCH.LKP_LGL_ENTY_CD
WHERE CNTRT_SRC_SYS_NM = 'LTCG'
AND TO_DATE('{cycle_date}','YYYY-MM-DD') BETWEEN EFF_STRT_DT AND EFF_STOP_DT
