SELECT
EFF_STRT_DT,
EFF_STOP_DT,
ORIGINTG_LGL_ENTY,
SRC_LGL_ENTY,
CNTRT_SRC_SYS_NM
FROM TIME_SCH.LKP_STAT_CMPY_TRNSLATN
WHERE CNTRT_SRC_SYS_NM = 'LTCG'
AND TO_DATE('${cycle_date}','YYYY-MM-DD') BETWEEN EFF_STRT_DT AND EFF_STOP_DT
