select from_utc_timestamp(current_timestamp, 'US/Central') as recorded_timestamp,
       source_system_name,
       original_cycle_date,
       original_batch_id,
       activity_accounting_id,
       transaction_number,
       row_number() over (
           partition by transaction_number
           order by activity_accounting_id
       ) as line_number,
       default_amount,
       default_amount_drvd,
       debit_credit_indicator,
       orig_gl_company,
       orig_gl_account,
       orig_gl_center,
       cast('{cycle_date}' as date) as cycle_date,
       cast('{batchid}' as int) as batch_id,
       secondary_ledger_code,
       transaction_date,
       data_type,
       source_system_nm_drvd,
       ledger_name_drvd,
       event_type_code_drvd,
       subledger_short_name_drvd,
       transaction_date_drvd,
       secondary_ledger_code_drvd,
       contractnumber,
       contractsourcesystemname,
       statutoryresidentstatecode,
       statutoryresidentstatecode_drvd,
       statutoryresidentcountrycode,
       ifrs17reportingcashflowtype,
       random_counter,
       old_error_message,
       error_record_aging_days,
       original_recorded_timestamp
from (
    select source_system_name,
           cast(original_cycle_date as date) as original_cycle_date,
           cast(original_batch_id as int) as original_batch_id,
           gl_activityaccountingid,
           transaction_number,
           default_amount,
           default_amount_drvd,
           debit_credit_indicator,
           orig_gl_company,
           orig_gl_account,
           orig_gl_center,
           secondary_ledger_code,
           transaction_date,
           data_type,
           source_system_nm_drvd,
           ledger_name_drvd,
           event_type_code_drvd,
           subledger_short_name_drvd,
           transaction_date_drvd,
           secondary_ledger_code_drvd,
           contractnumber,
           contractsourcesystemname,
           statutoryresidentstatecode,
           statutoryresidentstatecode_drvd,
           statutoryresidentcountrycode,
           ifrs17reportingcashflowtype,
           random_counter,
           old_error_message,
           error_record_aging_days,
           original_recorded_timestamp
    from source_df
    where len(error_message) = 0
)
