SELECT db.*,delta.operation_code
FROM (SELECT *
      FROM (SELECT uuid ,
                   segment_id ,
                   segment_sequence_number ,
                   management_code ,
                   coalesce(management_code_override,
                            c_management_code,
                            management_code) as management_cd ,
                   coalesce(resident_state_override,
                            c_resident_state,
                            resident_state) as resident_state ,
                   ordinal_position ,
                   statutory_company_code as statutory_company_cd ,
                   coalesce(contract_form_override,
                            c_contract_form,
                            contract_form) as contract_form ,
                   coalesce(processing_system_id_override,
                            c_processing_system_id,
                            processing_system_id) as processing_system_id ,
                   coalesce(contract_issue_country_code_override,
                            c_contract_issue_country_code,
                            contract_issue_country_code) as contract_issue_country_code ,
                   coalesce(contract_participation_indicator_override,
                            c_contract_participation_indicator,
                            contract_participation_indicator) as contract_participation_indicator ,
                   coalesce(group_indiv_ind_override,
                            c_group_indiv_ind,
                            group_indiv_ind) as group_indiv_ind ,
                   coalesce(company_code_override, c_company_code, company_code) as company_code ,
                   coalesce(last_fin_process_date_override,
                            c_last_fin_process_date,
                            last_fin_process_date) as last_fin_process_date ,
                   coalesce(key_qualifier_override,
                            c_key_qualifier,
                            key_qualifier) as key_qualifier ,
                   coalesce(statutory_company_code_override,
                            c_statutory_company_code,
                            statutory_company_code) as statutory_company_code ,
                   coalesce(legal_company_code_override,
                            c_legal_company_code,
                            legal_company_code) as legal_company_code ,
                   coalesce(source_legal_entity_code_override,
                            c_source_legal_entity_code,
                            source_legal_entity_code) as source_legal_entity_code ,
                   coalesce(plan_code_override, c_plan_code, plan_code) as plan_code ,
                   coalesce(qual_non_qual_ind_override,
                            c_qual_non_qual_ind,
                            qual_non_qual_ind) as qual_non_qual_ind ,
                   coalesce(policy_issue_state_override,
                            c_policy_issue_state,
                            policy_issue_state) as policy_issue_state ,
                   coalesce(contract_option_issue_state_code_override,
                            c_contract_option_issue_state_code,
                            contract_option_issue_state_code) as contract_option_issue_state_code ,
                   coalesce(policy_issue_age_override,
                            c_policy_issue_age,
                            policy_issue_age) as policy_issue_age ,
                   coalesce(contract_option_issue_age_override,
                            c_contract_option_issue_age,
                            contract_option_issue_age) as contract_option_issue_age ,
                   coalesce(policy_issue_date_override,
                            c_policy_issue_date,
                            policy_issue_date) as policy_issue_date ,
                   coalesce(contract_issue_month_override,
                            c_contract_issue_month,
                            contract_issue_month) as contract_issue_month ,
                   coalesce(contract_issue_year_override,
                            c_contract_issue_year,
                            contract_issue_year) as contract_issue_year ,
                   coalesce(policy_eff_date_override,
                            c_policy_eff_date,
                            policy_eff_date) as policy_eff_date ,
                   coalesce(contract_effective_month_override,
                            c_contract_effective_month,
                            contract_effective_month) as contract_effective_month ,
                   coalesce(contract_effective_year_override,
                            c_contract_effective_year,
                            contract_effective_year) as contract_effective_year ,
                   coalesce(contract_number_numeric_id_override,
                            c_contract_number_numeric_id,
                            contract_number_numeric_id) as contract_number_numeric_id ,
                   coalesce(contract_option_duration_in_months_override,
                            c_contract_option_duration_in_months,
                            contract_option_duration_in_months) as contract_option_duration_in_months ,
                   coalesce(contract_source_marketing_organization_code_override,
                            c_contract_source_marketing_organization_code,
                            contract_source_marketing_organization_code) as contract_source_marketing_organization_code ,
                   coalesce(contract_modeling_business_unit_group_override,
                            c_contract_modeling_business_unit_group,
                            contract_modeling_business_unit_group) as contract_modeling_business_unit_group ,
                   coalesce(contract_dac_group_override,
                            c_contract_dac_group,
                            contract_dac_group) as contract_dac_group ,
                   coalesce(contract_option_modeling_type_group_indicator_override,
                            c_contract_option_modeling_type_group_indicator,
                            contract_option_modeling_type_group_indicator) as contract_option_modeling_type_group_indicator ,
                   batchid ,
                   row_number() OVER(PARTITION BY key_qualifier,
                                             company_code,
                                             segment_id,
                                             ordinal_position
                                    ORDER BY cast(batchid as int) desc, segment_sequence_number desc) as row_num
            FROM {source_database}.gdqp5clprodsegmentdb
            WHERE cast(batchid as int) <= (batchid)) db
      WHERE row_num = 1) db
LEFT JOIN gdqp5deltaextract_mainfile_keys delta
       ON db.key_qualifier = delta.key_qualifier
      AND db.company_code = delta.company_code
      AND delta.segment_id = 'DB';