SELECT ACTVTY_AMT_TYP,
       ACTVTY_SRC_SYS_NAME,
       ACTVTY_SRC_TRN_CD,
       ACTVTY_ACCTNG_MEMO_CD,
       ACTVTY_FRST_YR_RNWL_IND,
       ACTVTY_TYP,
       ACTVTY_TYP_GRP,
       ACTSRCSYS_ACG_BAL_ENT_IND
FROM TIME_SCH.LKP_ACTVTY_TYP_TYPGRP
WHERE ACTVTY_SRC_SYS_NAME = 'Bestow'
