SELECT ACT_MNY_MTHD_DESC,
       ACT_SRC_SYS_NAME,
       SRC_ACT_MNY_MTHD
FROM TIME_SCH.LKP_ACT_MNY_MTHD
WHERE ACT_SRC_SYS_NAME = 'Bestow'
  AND ACT_SRC_TRXN_CD = '~'
  AND ACT_RVRSL_CD = '~'
  AND DEPT_CD = '~'
  AND DESK_CD = '~'
