SELECT ACT_MNY_MTHD_DESC,
       ACT_SRC_SYS_NAME,
       ACT_SRC_TRXN_CD
FROM TIME_SCH.LKP_ACT_MNY_MTHD
WHERE ACT_SRC_SYS_NAME = 'Bestow'
  AND ACT_RVRSL_CD = '~'
  AND DEPT_CD = '~'
  AND DESK_CD = '~'
  AND SRC_ACT_MNY_MTHD = '~'
