SELECT 
       ACT_SRCSYS_ACG_BAL_ENT_IND,
       ACTVTY_SRC_TRXN_CD,
       ACTVTY_SRC_ACCTNG_MEMO_CD,
       ACTVTY_SRC_SYS_NM
FROM TIME_SCH.LKP_ACT_SRCSYS_ACG_BAL_ENT_IND
WHERE ACTVTY_SRC_SYS_NM = 'Bestow'