SELECT a.uiddocumentgroupkey,
a.fundloadablefile,
a.fundindicator,
a.fundstudydate,
a.fundinforcedate,
a.fundnumber,
a.fundcompany,
a.productfundticker,
a.fundname,
a.fundcusip,
a.fundcusipticker,
a.fundtypeid,
a.fundcategory,
a.fundclass,
a.funddynamicseparateaccountflag,
a.fundselfhedgingseparateaccountflag,
a.fundgainlossfee,
a.load_date,
a.batchid
FROM (SELECT generatesameuuid(concat(alm.fundnumber,':', alm.fundregion)) as uiddocumentgroupkey,
coalesce(alm.loadablefile_override, alm.c_loadablefile, alm.loadablefile) as fundloadablefile,
coalesce(alm.indicator_override, alm.c_indicator, alm.indicator) as fundindicator,
coalesce(alm.studydate_override, alm.c_studydate, alm.studydate) as fundstudydate,
coalesce(alm.inforcedate_override, alm.c_inforcedate, alm.inforcedate) as fundinforcedate,
coalesce(alm.fundnumber_override, alm.c_fundnumber, alm.fundnumber) as fundnumber,
coalesce(alm.productfundticker_override, alm.c_productfundticker, alm.productfundticker) as productfundticker,
coalesce(alm.fundregion_override, alm.c_fundregion, alm.fundregion) as fundcompany,
coalesce(alm.fundname_override, alm.c_fundname, alm.fundname) as fundname,
coalesce(alm.cusip_override, alm.c_cusip, alm.cusip) as fundcusip,
coalesce(alm.cusipticker_override, alm.c_cusipticker, alm.cusipticker) as fundcusipticker,
coalesce(alm.fundtype_override, alm.c_fundtype, alm.fundtype) as fundtypeid,
coalesce(alm.fundcategory_override, alm.c_fundcategory, alm.fundcategory) as fundcategory,
coalesce(alm.fundclass_override, alm.c_fundclass, alm.fundclass) as fundclass,
coalesce(alm.funddynamicseparateaccountflag_override, alm.c_funddynamicseparateaccountflag, alm.funddynamicseparateaccountflag) as funddynamicseparateaccountflag,
coalesce(alm.fundselfhedgingseparateaccountflag_override, alm.c_fundselfhedgingseparateaccountflag, alm.fundselfhedgingseparateaccountflag) as fundselfhedgingseparateaccountflag,
coalesce(alm.gl_override, alm.c_gl, alm.gl) as fundgainlossfee,
'{cycle_date}' as load_date,
{batchid} as batchid,
row_number() OVER(PARTITION BY alm.fundnumber,
alm.fundregion
ORDER BY alm.time_stamp desc, cast(alm.batchid as int) desc) as seq_num
FROM (SELECT *
FROM {source_database}.gdqalmfundmapping
WHERE cast(batchid as int) = {batchid}) alm)a
WHERE a.seq_num = 1;