select from_utc_timestamp(CURRENT_TIMESTAMP, 'US/Central') as recorded_timestamp,
       source_system_name,
       original_cycle_date,
       original_batch_id,
       activity_accounting_id,
       transaction_number,
       row_number() over (
           partition by transaction_number
           order by activity_accounting_id
       ) as line_number,
       default_amount,
       default_amount_drvd,
       debit_credit_indicator,
       orig_gl_company,
       orig_gl_account,
       orig_gl_center,
       orig_gl_company_drvd,
       orig_gl_center_drvd,
       orig_gl_account_drvd,
       cast('{cycle_date}' as date) as cycle_date,
       cast({batchid} as int) as batch_id,
       gl_application_area_code,
       gl_source_code,
       secondary_ledger_code,
       transaction_date,
       data_type,
       source_system_nm_drvd,
       ledger_name_drvd,
       event_type_code_drvd,
       subledger_short_name_drvd,
       transaction_date_drvd,
       gl_source_code_drvd,
       secondary_ledger_code_drvd,
       contractnumber,
       contractsourcesystemname,
       statutoryresidentstatecode,
       statutoryresidentstatecode_drvd,
       statutoryresidentcountrycode,
       ifrs17cohort,
       ifrs17grouping,
       ifrs17measurementmodel,
       ifrs17portfolio,
       ifrs17profitability,
       ifrs17reportingcashflowtype,
       activitysourcectransactioncode,
       sourcesystemactivitydescription,
       sourcesystemgeneralledgeraccountnumber,
       plancode,
       checknumber,
       random_counter,
       old_error_message,
       error_record_aging_days,
       original_recorded_timestamp
from (
         select source_system_name,
                cast(original_cycle_date as date) as original_cycle_date,
                cast(original_batch_id as int) original_batch_id,
                gl_activityaccountingid,
                transaction_number,
                default_amount,
                default_amount_drvd,
                debit_credit_indicator,
                orig_gl_company,
                orig_gl_account,
                orig_gl_center,
                orig_gl_company_drvd,
                orig_gl_center_drvd,
                orig_gl_account_drvd,
                gl_application_area_code,
                gl_source_code,
                secondary_ledger_code,
                transaction_date,
                data_type,
                source_system_nm_drvd,
                ledger_name_drvd,
                event_type_code_drvd,
                subledger_short_name_drvd,
                transaction_date_drvd,
                gl_source_code_drvd,
                secondary_ledger_code_drvd,
                contractnumber,
                contractsourcesystemname,
                statutoryresidentstatecode,
                statutoryresidentstatecode_drvd,
                statutoryresidentcountrycode,
                ifrs17cohort,
                ifrs17grouping,
                ifrs17measurementmodel,
                ifrs17portfolio,
                ifrs17profitability,
                ifrs17reportingcashflowtype,
                activitysourcectransactioncode,
                sourcesystemactivitydescription,
                sourcesystemgeneralledgeraccountnumber,
                plancode,
                checknumber,
                random_counter,
                old_error_message,
                error_record_aging_days,
                original_recorded_timestamp
         from source_df
         where len(error_message) = 0
     )
