import os
# import os for filesystem operations
target_dir = r'C:\Users\shany\OneDrive\Desktop\findw-redshift\findw\ddls\tables\erpdwworking'
# set the folder where files should be created
names = [
'wrk_affinity_generalLedger_header.sql'
,'wrk_affinity_generalLedger_line_item.sql'
,'wrk_ahd_contractplancodeetails.sql'
,'wrk_ahd_contractorinsurancetreatycompldassignment.sql'
,'wrk_ahd_generalLedger_header.sql'
,'wrk_ahd_generalLedger_line_item.sql'
,'wrk_ahdfuturefirst_generalLedger_header.sql'
,'wrk_ahdfuturefirst_generalLedger_line_item.sql'
,'wrk_arr_contractplancodeetails.sql'
,'wrk_arr_contractorinsurancetreatycompldassignment.sql'
,'wrk_arr_generalLedger_header.sql'
,'wrk_arr_generalLedger_header_contractnumberlevelreserves.sql'
,'wrk_arr_generalLedger_line_item.sql'
,'wrk_arr_generalLedger_line_item_contractnumberlevelreserves.sql'
,'wrk_bestow_generalLedger_header.sql'
,'wrk_bestow_generalLedger_line_item.sql'
,'wrk_clearwater_generalLedger_header.sql'
,'wrk_clearwater_generalLedger_line_item.sql'
,'wrk_cyberlife0001lfrs17_generalLedger_header.sql'
,'wrk_cyberlife0001lfrs17_generalLedger_line_item.sql'
,'wrk_cyberlife1001tlbfrs17_generalLedger_header.sql'
,'wrk_cyberlife1001tlbfrs17_generalLedger_line_item.sql'
,'wrk_cyberlife9701lfrs17_generalLedger_header.sql'
,'wrk_cyberlife9701lfrs17_generalLedger_line_item.sql'
,'wrk_erpdw_accounts_payable_vendor_master.sql'
,'wrk_erpdw_generalledgerjournaldetail.sql'
,'wrk_erpdw_generalledgertrialbalance.sql'
,'wrk_erpdw_subledgerjournallinedetail.sql'
,'wrk_fsps_generalLedger_header.sql'
,'wrk_fsps_generalLedger_line_item.sql'
,'wrk_geac_accounts_payable_header.sql'
,'wrk_geac_accounts_payable_line_item.sql'
,'wrk_geac_accounts_payable_vendor.sql'
,'wrk_geac_generalLedger_header.sql'
,'wrk_geac_generalLedger_line_item.sql'
,'wrk_genesyslfrs17_generalLedger_header.sql'
,'wrk_genesyslfrs17_generalLedger_line_item.sql'
,'wrk_horizonlfrs17_generalLedger_header.sql'
,'wrk_horizonlfrs17_generalLedger_line_item.sql'
,'wrk_icosexaminerceded_generalLedger_header.sql'
,'wrk_icosexaminerceded_generalLedger_line_item.sql'
,'wrk_icosexaminerdocdir_generalLedger_header.sql'
,'wrk_icosexaminerdocdir_generalLedger_line_item.sql'
,'wrk_illuminlifr17_generalLedger_header.sql'
,'wrk_illuminlifr17_generalLedger_line_item.sql'
,'wrk_investranet_generalLedger_header.sql'
,'wrk_investranet_generalLedger_line_item.sql'
,'wrk_lewirebot_generalLedger_header.sql'
,'wrk_lewirebot_generalLedger_line_item.sql'
,'wrk_lifecommlfrs17_generalLedger_header.sql'
,'wrk_lifecommlfrs17_generalLedger_line_item.sql'
,'wrk_lifepro109lfrs17_generalLedger_header.sql'
,'wrk_lifepro109lfrs17_generalLedger_line_item.sql'
,'wrk_lifepro111lfrs17_generalLedger_header.sql'
,'wrk_lifepro111lfrs17_generalLedger_line_item.sql'
,'wrk_lifepro119_generalLedger_header.sql'
,'wrk_lifepro119_generalLedger_line_item.sql'
,'wrk_ltcg_generalLedger_header.sql'
,'wrk_ltcg_generalLedger_line_item.sql'
,'wrk_ltcghybrid_generalLedger_header.sql'
,'wrk_ltcghybrid_generalLedger_line_item.sql'
,'wrk_mantisflfrs17_generalLedger_header.sql'
,'wrk_mantisflfrs17_generalLedger_line_item.sql'
,'wrk_mkdb_currency_rates.sql'
,'wrk_mclslfrs17_generalLedger_header.sql'
,'wrk_mclslfrs17_generalLedger_line_item.sql'
,'wrk_murex_generalLedger_header.sql'
,'wrk_murex_generalLedger_line_item.sql'
,'wrk_oracleap_accounts_payable_vendor.sql'
,'wrk_oracleap_accountspayableescheatmentcheck.sql'
,'wrk_oracleap_accountspayableescheatmentinvoice.sql'
,'wrk_oracleap_paymentdetail.sql'
,'wrk_oraclesubledgerjournallinedetail.sql'
,'wrk_oracledmcs_edmcshierarchy.sql'
,'wrk_oraclefah_subledgerjournallinedetail.sql'
,'wrk_oraclegl_generalledgerjournaldetail.sql'
,'wrk_oraclegl_generalledgertrialbalance.sql'
,'wrk_p3dss_generalLedger_header.sql'
,'wrk_p3dss_generalLedger_line_item.sql'
,'wrk_p5dss_generalLedger_header.sql'
,'wrk_p5dss_generalLedger_line_item.sql'
,'wrk_p7dss_generalLedger_header.sql'
,'wrk_p7dss_generalLedger_line_item.sql'
,'wrk_performanceplus_generalLedger_header.sql'
,'wrk_performanceplus_generalLedger_line_item.sql'
,'wrk_processoroneexton_generalLedger_header.sql'
,'wrk_processoroneexton_generalLedger_line_item.sql'
,'wrk_processoroneorplano_generalLedger_header.sql'
,'wrk_processoroneorplano_generalLedger_line_item.sql'
,'wrk_revoport_generalLedger_header.sql'
,'wrk_revoport_generalLedger_line_item.sql'
,'wrk_revport_generalLedger_header.sql'
,'wrk_revport_generalLedger_line_item.sql'
,'wrk_sailpoint_oracleworkercountry.sql'
,'wrk_sailpoint_oracleworkerdetails.sql'
,'wrk_tagetik_generalLedger_header.sql'
,'wrk_tagetik_generalLedger_line_item.sql'
,'wrk_talasia_generalLedger_header.sql'
,'wrk_talasia_generalLedger_line_item.sql'
,'wrk_tip_accountspayableescheatmentcheck.sql'
,'wrk_tpaclaims_generalLedger_header.sql'
,'wrk_tpaclaims_generalLedger_line_item.sql'
,'wrk_tpadlfrs17_generalLedger_header.sql'
,'wrk_tpadlfrs17_generalLedger_line_item.sql'
,'wrk_tpapiflfrs17_generalLedger_header.sql'
,'wrk_tpapiflfrs17_generalLedger_line_item.sql'
,'wrk_upcs_accountspayableescheatmentcheck.sql'
,'wrk_vantage5_generalLedger_header.sql'
,'wrk_vantage5_generalLedger_line_item.sql'
,'wrk_vantage6_generalLedger_header.sql'
,'wrk_vantage6_generalLedger_line_item.sql'
,'wrk_vantage65_generalLedger_header.sql'
,'wrk_vantage65_generalLedger_line_item.sql'
,'wrk_vantage75_generalLedger_header.sql'
,'wrk_vantage75_generalLedger_line_item.sql'
,'wrk_yardi_generalLedger_header.sql'
]
# list of all filenames to create
os.makedirs(target_dir, exist_ok=True)
# make target directory if missing
for n in names:
# start loop over filenames
  f = os.path.join(target_dir, n)
# build full path for each file
  if not os.path.exists(f):
# only create when file does not already exist
    open(f, 'w').close()
# create an empty file
  print('Created or exists:', f)
# print status per file
